queue_med/config/routes.rb
Rails.application.routes.draw do

  resources :patients

  resources :organizations

  get 'sessions/login'
  resources :users
  get 'auth' => 'users#auth'
  post 'auth' => 'users#check_auth'
  get 'logout' => 'users#logout'
  get 'patients/:id/new_comission' => 'patients#new_comission'
  patch 'patients/:id/new_comission' => 'patients#create_comission'
  get 'patients/:id/new_result' => 'patients#new_result'
  patch 'patients/:id/new_result' => 'patients#create_result'
  root 'users#index'

end

queue_med/app/models/patient.rb
class Patient < ActiveRecord::Base
	belongs_to :organization
	belongs_to :result
	belongs_to :report
	belongs_to :diagnosis
end

queue_med/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    require 'date'
	before_filter :o_first || :o_second, :only => [:index, :show]
    before_filter :o_first, :only => [:new, :create, :edit, :update, :new_comission, :create_comission]
    before_filter :o_second, :only => [:new_result, :create_result]

	#before_filter :o_second, :only => [:index]
	def index
        @patients = Patient.all
    	@current_user = User.find session[:user_id]
    		if @current_user.type_role==2
    			render 'index_1'
    		end
    		if @current_user.type_role==3
    			render 'index_2'
    		end
            if @current_user.type_role==1
                redirect_to(:controller => 'users', :action => 'index')
            end
	end

    def show
        @patient = Patient.find(params[:id]) 
        @current_user = User.find session[:user_id]
            if @current_user.type_role==2
                render 'show_1'
            end
            if @current_user.type_role==3
                render 'show_2'
            end
            if @current_user.type_role==1
                redirect_to(:controller => 'users', :action => 'index')
            end
    end

    def new
        @patient = Patient.new
    end

    def create 
        #params[:register] = Date.today
        @patient = Patient.new(register_params)
        if @patient.save 
            @patient.update_attribute(:register, Date.today)
            redirect_to :action => 'index'
        else
            render 'new'
        end
    end

    def edit
        @patient = Patient.find(params[:id])
    end

    def update 
        @patient = Patient.find(params[:id])
        if @patient.update_attributes(register_params)
            redirect_to(:action => 'show', :id => @patient.id)
        else
            render('index')
        end
    end

    def new_comission
        @patient = Patient.find(params[:id])
    end

    def create_comission
        @patient = Patient.find(params[:id])
        if @patient.update_attributes(comission)
            @patient.update_attribute(:date_report, Date.today)
            @digit = Digits.find(1)
            if @patient.numreport==0 
                @digit.update_attribute(:report, @digit.report+1)
                @patient.update_attribute(:numreport, @digit.report)
            end
            if ((@patient.numdirection==0)&&(@patient.report_id==1))
                @digit.update_attribute(:direction, @digit.direction+1)
                @patient.update_attribute(:numdirection, @digit.direction)
            end
            redirect_to :action => 'show'
        else
            render 'new_comission'
        end
    end

    def new_result
        @patient = Patient.find(params[:id])
    end

    def create_result
        @patient = Patient.find(params[:id])
        if @patient.update_attributes(result)
            @digit = Digits.find(1)
            if @patient.numresult==0 
                @digit.update_attribute(:report, @digit.report+1)
                @patient.update_attribute(:numreport, @digit.report)
            end
            redirect_to :action => 'show'
        else
            render 'new_result'
        end
    end

    def delete
        @patient = Patient.find(params[:id])
    end
    
    def destroy
        @patient = Patient.find(params[:id]).destroy
        redirect_to(:action => 'index')
    end

private
    def register_params
        params.require(:patient).permit(:surname, :name, :patronymic, :birthday, :phone, :snils, :diagnosis_id)
    end

    def comission
        params.require(:patient).permit(:report_id, :numreport, :organization_id, :numdirection)
    end

    def result
        params.require(:patient).permit(:proc_begin, :proc_end, :result_id)
    end
end

queue_med/app/helpers/patients_helper.rb
module PatientsHelper
end

queue_med/app/views/patients/_patient.html.erb
<% diagnoses = Diagnosis.all.map{|diagnosis| [diagnosis.name, diagnosis.id]} %>
<%= form_for(@patient) do |f| %>
<p>
    <%= f.label 'Фамилия: ' %><%= f.text_field :surname %>
</p>
<p>
    <%= f.label 'Имя: ' %><%= f.text_field :name %>
</p>
<p>
    <%= f.label 'Отчество: ' %><%= f.text_field :patronymic %>
</p>
<p>
    <%= f.label 'Дата рождения: ' %><%= f.date_field :birthday %>
</p>
<p>
    <%= f.label 'Телефон: ' %><%= f.telephone_field :phone %>
</p>
<p>
	<%= f.label 'СНИЛС: ' %><%= f.text_field :snils %>
<p>
<p>
	<%= f.label 'Диагноз: ' %><%= f.select :diagnosis_id, diagnoses %>
</p>
<p>	
    <%= f.submit 'Отправить' %>
</p>
<% end %>

queue_med/app/views/patients/edit.html.erb
<h1>Изменение пользователя</h1>
<%= render 'patient' %>
<%= link_to 'Назад', patients_path %>

queue_med/app/views/patients/index_1.html.erb
<h1>Пациенты /Первичное учреждение/</h1>
<table  class="table table-bordered table-stripped">
    <tr class="warning"><th>ФИО</th><th>Дата рождения</th><th>Контактный телефон</th><th>Зарегистрирован</th><th>Редактирование</th></tr>
    <% @patients.each do |patient| %>
    <tr><td><%= patient.surname %> <%= patient.name %> <%= patient.patronymic %></td><td><%= patient.birthday %></td><td><%= patient.phone %></td><td><%= patient.register %></td><td><%= link_to 'Изменить регистрацию', edit_patient_path(patient.id) %> | <%= link_to 'Просмотр', patient %> | <%= link_to 'Комиссия', :controller => 'patients', :action => 'new_comission', id: patient.id %> | <%= link_to 'Удалить', patient, method: :delete, data: { confirm: 'Вы уверены?' } %></td></tr>
    <% end %>
</table>
<p><%= link_to 'Новый пациент', new_patient_path %></p>

queue_med/app/views/patients/index_2.html.erb
<h1>Пациенты /Вторичное учреждение/</h1>
<table class="table table-bordered table-stripped">
    <tr class="warning"><th>ФИО</th><th>Дата рождения</th><th>Зарегистрирован</th><th>Редактирование</th></tr>
    <% @patients.each do |patient| %>
    <tr><td><%= patient.surname %> <%= patient.name %> <%= patient.patronymic %></td><td><%= patient.birthday %></td><td><%= patient.register %></td><td><%= link_to 'Просмотр', patient %> | <%= link_to 'Результат', :controller => 'patients', :action => 'new_result', id: patient.id %>  </td></tr>
    <% end %>
</table>

queue_med/app/views/patients/new.html.erb
<h1>Регистрация пациента</h1>
<%= render 'patient' %>
<%= link_to 'Назад', patients_path %>

queue_med/app/views/patients/new_comission.html.erb
<% reports = Report.all.map{|report| [report.name, report.id]} %> 
<% orgs = Organization.where(type_org: '3').all.map{|organization| [organization.name, organization.id]} %>
  <h1>Комиссия</h1>
  <%= form_for @patient, url: 'new_comission' do |f| %>
  <p>Дата Комиссии <%= f.date_field(:date_report) %></p>
  <p>Результат: <%= f.select(:report_id, options_for_select(reports, 3)) %></p> 
  <p>Организация: <%= f.select(:organization_id, options_for_select(orgs)) %></p>
  <%= f.submit("Сохранить") %>
  <% end %>

 <script type="text/javascript">
	$("#report_id").change(function(){
		if ($("#report_id").val()!="1")
			$("#organization_id").attr('disabled', 'disabled');	
		else
			$("#organization_id").removeAttr('disabled');
	})
</script>
 

queue_med/app/views/patients/new_result.html.erb
<% results = Result.all.map{|result| [result.name, result.id]} %> 
  <h1>Процедура</h1>
  <%= form_for @patient, url: 'new_result' do |f| %>
  <p>Дата начала процедуры <%= f.date_field(:proc_begin) %></p>
  <p>Дата окончания процедуры <%= f.date_field(:proc_end) %></p>
  <p>Результат: <%= f.select(:result_id, options_for_select(results)) %></p> 
  <%= f.submit("Сохранить") %>
  <% end %>

 
 

queue_med/app/views/patients/show_1.html.erb
<h1>Просмотр пациента /Первичное учреждение/</h1>
<p>
    <b>Фамилия:</b> <%= @patient.surname %><br />
    <b>Имя:</b> <%= @patient.name %><br />
    <b>Отчество:</b> <%= @patient.patronymic %><br />
    <b>Дата рождения:</b> <%= @patient.birthday %><br />
    <b>Контактный телефон:</b> <%= @patient.phone %><br />
    <b>СНИЛС:</b> <%= @patient.snils %><br />
    <b>Диагноз:</b> <%= @patient.diagnosis.try(:name) %><br />
    <b>Зарегистрирован:</b> <%= @patient.register %><br />
    <b>Дата комиссии: </b> <%= @patient.date_report %><br />
    <b>Решение комиссии: </b> <%= @patient.report.try(:name) %><br />
    <b>Протокол комиссии №: </b> <%= @patient.numreport %><br />
    <b>Организация для проведения процедуры: </b> <%= @patient.organization.name %><br />
    <b>Направление №: </b> <%= @patient.numdirection %><br />
    <%= link_to 'Изменить регистрационные данные', edit_patient_path(@patient) %><br />
    <%= link_to 'Комиссия', :controller => 'patients', :action => 'new_comission', :id => @patient.id %><br />
    <%= link_to 'Назад', patients_path %>
</p>

queue_med/app/views/patients/show_2.html.erb
<h1>Просмотр пациента /Вторичное учреждение/</h1>
<p>
    <b>Фамилия:</b> <%= @patient.surname %><br />
    <b>Имя:</b> <%= @patient.name %><br />
    <b>Отчество:</b> <%= @patient.patronymic %><br />
    <b>Дата рождения:</b> <%= @patient.birthday %><br />
    <b>Контактный телефон:</b> <%= @patient.phone %><br />
    <b>СНИЛС:</b> <%= @patient.snils %><br />
    <b>Диагноз:</b> <%= @patient.diagnosis.try(:name) %><br />
    <b>Организация для проведения процедуры: </b> <%= @patient.organization.name %><br />
    <b>Направление №: </b> <%= @patient.numdirection %><br />
    <b>Дата начала процедуры: </b> <%= @patient.proc_begin %><br />
    <b>Дата окончания процедуры: </b> <%= @patient.proc_end %><br />
    <b>Результат процедуры: </b> <%= @patient.result.try(:name) %><br />
    <%= link_to 'Изменить регистрационные данные', edit_patient_path(@patient) %><br />
    <%= link_to 'Комиссия', :controller => 'patients', :action => 'new_comission', :id => @patient.id %><br />
    <%= link_to 'Результат комиссии', :controller => 'patients', :action => 'new_result', :id => @patient.id %><br />
    <%= link_to 'Назад', patients_path %>
</p>