queue_med/config/routes.rb
Rails.application.routes.draw do

  resources :patients

  resources :organizations

  get 'sessions/login'
  resources :users
  get 'auth' => 'users#auth'
  post 'auth' => 'users#check_auth'
  get 'logout' => 'users#logout'
  get 'patients/:id/new_comission' => 'patients#new_comission'
  patch 'patients/:id/new_comission' => 'patients#create_comission'
  get 'patients/:id/new_result' => 'patients#new_result'
  patch 'patients/:id/new_result' => 'patients#create_result'
  root 'users#index'

end

queue_med/app/models/organization.rb
class Organization < ActiveRecord::Base

end

queue_med/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
    before_filter :admin, :only => [:index, :new, :create]
      def index
      @organizations = Organization.all
  end

  def new
      @organization = Organization.new
  end

  def create
      @organization = Organization.new(organization_params)
      if @organization.save
          redirect_to(:action => 'index')
      else
          render('new')
      end
  end
    
  def edit
      @organization = Organization.find(params[:id])
  end

  def update
      @organization = Organization.find(params[:id])
      if @organization.update_attributes(organization_params)
          redirect_to(:action => 'index')     
      end
  end

  def delete
      @organization = User.find(params[:id])
  end
    
  def destroy
      @organization = User.find(params[:id]).destroy
      redirect_to(:action => 'index')
  end
    
private 
    def organization_params
        params.require(:organization).permit(:name, :type_org)
    end
end

queue_med/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

queue_med/app/views/organizations/_organization.html.erb
<% orgs = [['ЧОМИАЦ', '1'],['Первичное учреждение', '2'],['Учреждение, проводящее процедуру', '3']] %>
<%= form_for(@organization) do |f| %>
<p>
    <%= f.label 'Наименование:' %> <%= f.text_field :name %>
</p>
<p>
	<%= f.label 'Тип:' %> <%= f.select :type_org, orgs %>
</p>
<p>
    <%= f.submit 'Отправить' %>
</p>
<% end %>

queue_med/app/views/organizations/edit.html.erb
<h1>Изменение пользователя</h1>
<%= render 'organization' %>
<%= link_to 'Назад', organizations_path %>

queue_med/app/views/organizations/index.html.erb
<h1>Организации</h1>
<table border>
    <tr><th>ID</th><th>Название организации</th><th>Редактирование</th></tr>
    <% @organizations.each do |organization| %>
    <tr><td><%= organization.id %></td><td><%= organization.name %></td><td><%= link_to 'Изменить', edit_organization_path(organization.id) %> | <%= link_to 'Удалить', organization, method: :delete, data: { confirm: 'Вы уверены?' } %></td></tr>
    <% end %>
</table>
<p><%= link_to 'Новая организация', new_organization_path %></p>

queue_med/app/views/organizations/new.html.erb
<h1>Добавление организации</h1>
<%= render 'organization' %>
<%= link_to 'Назад', organizations_path %>